# Simplified: Front-End Skeleton
# https://github.com/andrewdisley/Front-End-Skeleton

# https://jekyllrb.com/docs/permalinks/
permalink: /events/:title/

# Configure Title, ID, Domain, URLs and Google Analytics ID
title: "GeekUp"
id: geekup-org
domain: geekup.org
url: https://geekup.org
assets_url: /assets/
google_ga4_id: G-BLFDV1ZFW9

# Show future posts
future: true

# Set environment
# development, staging, production
env: production

# Cache buster
#assets_cache_buster:

exclude: ['Rakefile', 'geekup.ics', 'README']
